# version: "3.9" # Specify the Compose file format version.

services:
  angular-app: # Name of the service.
    build:
      context: . # Use the current directory for the Dockerfile.
      dockerfile: Dockerfile # Specify the Dockerfile name.
    ports:
      - "8080:80" # Map port 80 inside the container to port 8080 on the host.
    container_name: angular-app-container # Optional: Name of the container.
    restart: unless-stopped # Restart policy for the container.
