pipeline {
    agent {
      docker {
        image 'node:22.13.1'
      }
    }

    stages {
        stage('Install Dependencies') {
            steps {
                script {
                    dir('jasmine-karma-documentation') {
                        sh 'npm install'
                    }
                }
            }
        }

        stage('Build Angular App') {
            steps {
                script {
                    dir('jasmine-karma-documentation') {
                        sh 'ng build --configuration=production'
                    }
                }
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    dir('jasmine-karma-documentation') {
                        sh 'ng test --code-coverage --watch=false'
                    }
                }
            }
        }

        stage('Archive Build Artifacts') {
            steps {
                archiveArtifacts artifacts: 'jasmine-karma-documentation/dist/**/*', fingerprint: true
            }
        }
    }
}
