pipeline {
    agent any

    tools {
      nodejs "NodeJS 22.13.1"
    }

    stages {
        stage('Install Dependencies') {
            steps {
                script {
                    dir('jasmine-karma-documentation') {
                        sh 'npm install'
                    }
                }
            }
        }

        stage('Build Angular App') {
            steps {
                script {
                    dir('jasmine-karma-documentation') {
                        sh 'ng -- build --configuration=production'
                    }
                }
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    dir('jasmine-karma-documentation') {
                        sh 'ng -- test --code-coverage --watch=false'
                    }
                }
            }
        }

        // I've commented this because I'm getting the error: ERROR: No artifacts found that match the file pattern "dist/jasmine-karma-documentation/browser". Configuration error?
        // And also I don't know why this part of code is needed.
        stage('Archive Build Artifacts') {
              steps {
                  // script {
                      // dir('jasmine-karma-documentation') {
                  archiveArtifacts artifacts: 'jasmine-karma-documentation/dist/**', fingerprint: true
                      // }
                  // }
              }
        }
    }
}
