// pipeline {
//     agent {
//         docker {
//             image 'node:20'
//         }
//     }

//     stages {
//         stage('Install Dependencies') {
//             steps {
//                 script {
//                     dir('jasmine-karma-documentation') {
//                         sh 'npm install'
//                     }
//                 }
//             }
//         }

//         stage('Build Angular App') {
//             steps {
//                 script {
//                     dir('jasmine-karma-documentation') {
//                         sh 'npx ng build --configuration=production'
//                     }
//                 }
//             }
//         }

//         stage('Run Tests') {
//             steps {
//                 script {
//                     dir('jasmine-karma-documentation') {
//                         sh 'npx ng test --code-coverage --watch=false'
//                     }
//                 }
//             }
//         }

//         stage('Archive Build Artifacts') {
//             steps {
//                 archiveArtifacts artifacts: 'jasmine-karma-documentation/dist/**/*', fingerprint: true
//             }
//         }
//     }
// }


// pipeline {
//     agent any
//     stages {
//         stage('build') {
//             steps {
//                 script {
//                     dir('jasmine-karma-documentation') {
//                         sh 'npm install'
//                     }
//                 }
//             }
//         }
//     }
// }


pipeline {
    agent {
        docker {
            image 'node:20'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'node -v'
            }
        }
    }
}
