controller:
  image:
    registry: docker.io
    repository: zeroaninea/jenkins
    tag: custom
    pullPolicy: Always

  podTemplate:
    yaml: |
      apiVersion: v1
      kind: Pod
      spec:
        containers:
        - name: node-chrome
          image: cypress/included:latest
          command: ["sh", "-c", "apt-get update && apt-get install -y google-chrome-stable && tail -f /dev/null"]
          tty: true
          env:
            - name: CHROME_BIN
              value: "/usr/bin/google-chrome"
