apiVersion: apps/v1 # Specifies the API version of the Kubernetes resourses.
kind: Deployment # Defines that this is a Deployment resouse.
metadata:
  name: nginx-deployment # Names this Deyloyment "nginx-deployment".
spec:
  replicas: 2 # Creates 2 identical pods.
  selector:
    matchLabels:
      app: nginx # The Deployment will menage pods with the label `app: nginx`.
  template:
    metadata:
      labels:
        app: nginx # Lables the created pods with `app: nginx``.
    spec:
      containers:
        - name: nginx # Name of the container inside the pod.
          image: nginx:1.16 # Uses the `nginx:1.16` Docker image.
          resources:
            limits: # Sets resourse limits.
              memory: "128Mi" # Max memory 128MB.
              cpu: "500m" # Max CPU 500m (which means 0.5 CPU cores).
          ports:
            - containerPort: 80 # The container inside the pod listens on port 80.
