name: First Workflow
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Hello World
        run: echo "Hello, World!"

      - name: Simulating Error
        run: echo "error taking place"; exit 1

  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: job1
        run: echo "job1"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: job1
        run: echo "job1"
